# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88c5c8d82257df269159f983ac21a6621d873d7f86eac1983601b82ea4c22d8817f2807e8bf1a509848b54a6fe993e1f6bf9829033dbffb8068ac1a90da71a1b

test:
  secret_key_base: ea9e715cdf17998d0164e372efa07c4dbb3cdaa33f51fd1bb772b53d920dedee033c976406c68417c8a77167072abbe8f4c50fe541998494e77423597024b60b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
